### ISSUE TITLE
Box shadow opinion.

### ISSUE THREAD

**Issue by aranajhonny** [nickstanish/reprogressbars#2]
Hi, I think this project is great, but the box-shadow makes it uncomfortable should be optional. youtube and github do not have it I think it looks better without it

**Comment by nickstanish** [comment]
Youtube has it, but only on the end, and it pulses (You can test by throttling your network in chrome dev tools)
![image](https://cloud.githubusercontent.com/assets/1869157/21942660/935178e8-d993-11e6-84c3-be22fd422463.png)

Github has it, but it's pretty subtle: (`document.getElementById("js-pjax-loader-bar").classList.add('is-loading')`)
![image](https://cloud.githubusercontent.com/assets/1869157/21942719/c346c526-d993-11e6-8e59-6d9a805150f4.png)

![image](https://cloud.githubusercontent.com/assets/1869157/21942739/da9712b2-d993-11e6-87a6-bd8d4a685227.png)


However, I agree that it should be configurable/optional. I think that I will eventually expose a progress bar without styles (other than the width value) so that it is easy to customize, but for now a simple useShadow boolean prop could work.

**Comment by aranajhonny** [comment]
Okay, good luck with that, I'll close this issue.
